operator:
  name: fdb-kubernetes-operator-controller-manager
  image: foundationdb/fdb-kubernetes-operator
  tag: 0.24.0
  role: fdb-kubernetes-operator-manager-role
  rolebinding: fdb-kubernetes-operator-manager-rolebinding
  replicas: 1
  globalMode:
    enabled: false

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 500m
    memory: 256Mi
