apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: foundationdbclusters.apps.foundationdb.org
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.generation
    description: Latest generation of the spec
    name: Generation
    type: integer
  - JSONPath: .status.generations.reconciled
    description: Last reconciled generation of the spec
    name: Reconciled
    type: integer
  - JSONPath: .status.health.healthy
    description: Database health
    name: Healthy
    type: boolean
  group: apps.foundationdb.org
  names:
    kind: FoundationDBCluster
    plural: foundationdbclusters
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            automationOptions:
              properties:
                configureDatabase:
                  type: boolean
              type: object
            configured:
              type: boolean
            connectionString:
              type: string
            containers:
              items:
                type: object
              type: array
            customParameters:
              items:
                type: string
              type: array
            dataCenter:
              type: string
            databaseConfiguration:
              properties:
                regions:
                  items:
                    properties:
                      datacenters:
                        items:
                          properties:
                            id:
                              type: string
                            priority:
                              format: int64
                              type: integer
                            satellite:
                              format: int64
                              type: integer
                          type: object
                        type: array
                    type: object
                  type: array
              type: object
            faultDomain:
              properties:
                key:
                  type: string
                value:
                  type: string
                valueFrom:
                  type: string
                zoneCount:
                  format: int64
                  type: integer
                zoneIndex:
                  format: int64
                  type: integer
              type: object
            initContainers:
              items:
                type: object
              type: array
            logGroup:
              type: string
            mainContainer:
              properties:
                enableTls:
                  type: boolean
                env:
                  items:
                    type: object
                  type: array
                peerVerificationRules:
                  items:
                    type: string
                  type: array
                volumeMounts:
                  items:
                    type: object
                  type: array
              type: object
            nextInstanceID:
              format: int64
              type: integer
            pendingRemovals:
              type: object
            podLabels:
              type: object
            processCounts:
              properties:
                log:
                  format: int64
                  type: integer
                master:
                  format: int64
                  type: integer
                proxy:
                  format: int64
                  type: integer
                resolution:
                  format: int64
                  type: integer
                resolver:
                  format: int64
                  type: integer
                router:
                  format: int64
                  type: integer
                stateless:
                  format: int64
                  type: integer
                storage:
                  format: int64
                  type: integer
                transaction:
                  format: int64
                  type: integer
                unset:
                  format: int64
                  type: integer
              type: object
            resources:
              type: object
            runningVersion:
              type: string
            sidecarContainer:
              properties:
                enableTls:
                  type: boolean
                env:
                  items:
                    type: object
                  type: array
                peerVerificationRules:
                  items:
                    type: string
                  type: array
                volumeMounts:
                  items:
                    type: object
                  type: array
              type: object
            sidecarVariables:
              items:
                type: string
              type: array
            sidecarVersion:
              format: int64
              type: integer
            storageClass:
              type: string
            trustedCAs:
              items:
                type: string
              type: array
            version:
              type: string
            volumeSize:
              type: string
            volumes:
              items:
                type: object
              type: array
          required:
          - version
          - volumeSize
          type: object
        status:
          properties:
            databaseConfiguration:
              properties:
                regions:
                  items:
                    properties:
                      datacenters:
                        items:
                          properties:
                            id:
                              type: string
                            priority:
                              format: int64
                              type: integer
                            satellite:
                              format: int64
                              type: integer
                          type: object
                        type: array
                    type: object
                  type: array
              type: object
            generations:
              properties:
                needsConfigurationChange:
                  format: int64
                  type: integer
                reconciled:
                  format: int64
                  type: integer
              type: object
            health:
              properties:
                available:
                  type: boolean
                dataMovementPriority:
                  format: int64
                  type: integer
                fullReplication:
                  type: boolean
                healthy:
                  type: boolean
              type: object
            incorrectProcesses:
              type: object
            missingProcesses:
              type: object
            processCounts:
              properties:
                log:
                  format: int64
                  type: integer
                master:
                  format: int64
                  type: integer
                proxy:
                  format: int64
                  type: integer
                resolution:
                  format: int64
                  type: integer
                resolver:
                  format: int64
                  type: integer
                router:
                  format: int64
                  type: integer
                stateless:
                  format: int64
                  type: integer
                storage:
                  format: int64
                  type: integer
                transaction:
                  format: int64
                  type: integer
                unset:
                  format: int64
                  type: integer
              type: object
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
