# This file provides an example of a cluster with a backup running.
#
# The backup resource will bring up backup agents and start a backup. Once it
# is reconciled, you can run backup commands from the backup agent containers:
#
#     # Check Status
#     kubectl exec deployment/sample-cluster-backup-agents -- fdbbackup status
#
#     # List Backups
#     kubectl exec deployment/sample-cluster-backup-agents -- fdbbackup list -b "blobstore://minio@minio-service:9000?bucket=fdb-backups"
#
# This example uses configuration for a local MinIO instance, which is set up as
# part of the local testing environment for the operator. This instance has
# certificates stored in Kubernetes secrets, and credentials that are hardcoded
# in the YAML. This configuration is for testing purposes only. You will need to
# determine the appropriate way of managing certificates and credentials for
# your real environment and endpoints, as well as the appropriate backup
# solution to use. We use MinIO in our local tests due to its lightweight setup,
# but you can backup to any S3-compatible object storage service.
#
# If you are testing this in Docker Desktop, you can browse the local MinIO
# instance at https://localhost:9000. Note: This will use a certificate that
# is not in your browser's trust store, so you will get a security warning.
apiVersion: apps.foundationdb.org/v1beta1
kind: FoundationDBCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: sample-cluster
spec:
  version: 6.2.15
  volumeClaim:
    spec:
      resources:
        requests:
          storage: "16G"
  faultDomain:
    key: foundationdb.org/none
  processCounts:
    stateless: -1
  customParameters:
    - "knob_disable_posix_kernel_aio=1"
  podTemplate:
    spec:
      securityContext:
        fsGroup: 0
      containers:
        - name: foundationdb
          securityContext:
            runAsUser: 0
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
        - name: foundationdb-kubernetes-sidecar
          securityContext:
            runAsUser: 0
      initContainers:
        - name: foundationdb-kubernetes-init
          securityContext:
            runAsUser: 0
---
apiVersion: apps.foundationdb.org/v1beta1
kind: FoundationDBBackup
metadata:
  name: sample-cluster
spec:
  version: 6.2.15
  clusterName: sample-cluster
  accountName: minio@minio-service:9000
  snapshotPeriodSeconds: 60
  podTemplateSpec:
    spec:
      containers:
        - name: foundationdb
          env:
            - name: FDB_BLOB_CREDENTIALS
              value: /var/backup-credentials/credentials
            - name: FDB_TLS_CERTIFICATE_FILE
              value: /tmp/fdb-certs/tls.crt
            - name: FDB_TLS_CA_FILE
              value: /tmp/fdb-certs/tls.crt
            - name: FDB_TLS_KEY_FILE
              value: /tmp/fdb-certs/tls.key
          volumeMounts:
            - name: fdb-certs
              mountPath: /tmp/fdb-certs
            - name: backup-credentials
              mountPath: /var/backup-credentials
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 128Mi
          securityContext:
            runAsGroup: 0
            runAsUser: 0
      volumes:
        - name: backup-credentials
          secret:
            secretName: minio-credentials
        - name: fdb-certs
          secret:
            secretName: fdb-kubernetes-operator-secrets