# This file provides an example of a cluster that is sized for a production
# environment.
apiVersion: apps.foundationdb.org/v1beta1
kind: FoundationDBCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: sample-cluster
spec:
  version: 6.2.11
  podTemplate:
    spec:
      automountServiceAccountToken: false
      containers:
          - name: "foundationdb"
            resources:
              requests:
                cpu: 2
                memory: 8Gi
