# This file provides an example of a cluster you can run in a local testing
# environment.
apiVersion: apps.foundationdb.org/v1beta1
kind: FoundationDBCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: sample-cluster
spec:
  version: 6.2.20
  faultDomain:
    key: foundationdb.org/none
  services:
    headless: true
  processCounts:
    stateless: -1
    cluster_controller: 1
    storage: 4
  processes:
    general:
      customParameters:
        - "knob_disable_posix_kernel_aio=1"
        - "locality_test=1"
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: "16G"
      podTemplate:
        spec:
          securityContext:
            fsGroup: 0
          containers:
            - name: foundationdb
              securityContext:
                runAsUser: 0
              resources:
                requests:
                  cpu: 250m
                  memory: 128Mi
            - name: foundationdb-kubernetes-sidecar
              securityContext:
                runAsUser: 0
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
          initContainers:
            - name: foundationdb-kubernetes-init
              securityContext:
                runAsUser: 0
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
