# This file provides an example of a cluster you can run in a local testing
# environment to create a simultation of a multi-DC cluster.
#
# This requires variables to be interpolated for $dc, $logCount,
# and $connectionString
apiVersion: apps.foundationdb.org/v1beta1
kind: FoundationDBCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    cluster-group: sample-cluster
  name: sample-cluster-$dc
spec:
  version: 6.2.20
  faultDomain:
    key: foundationdb.org/none
  instanceIDPrefix: $dc
  dataCenter: $dc
  processCounts:
    stateless: -1
    log: $logCount
  seedConnectionString: $connectionString
  customParameters:
    - "knob_disable_posix_kernel_aio=1"
  databaseConfiguration:
    redundancy_mode: "double"
    usable_regions: 2
    regions:
      - datacenters:
          - id: dc1
            priority: 1
          - id: dc3
            satellite: 1
            priority: 1
        satellite_logs: 3
      - datacenters:
          - id: dc2
            priority: 0
          - id: dc3
            satellite: 1
            priority: 1
        satellite_logs: 3
  processes:
    general:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: "16G"
      podTemplate:
        spec:
          securityContext:
            fsGroup: 0
          containers:
            - name: foundationdb
              securityContext:
                runAsUser: 0
              resources:
                requests:
                  cpu: 250m
                  memory: 128Mi
            - name: foundationdb-kubernetes-sidecar
              securityContext:
                runAsUser: 0
          initContainers:
            - name: foundationdb-kubernetes-init
              securityContext:
                runAsUser: 0
